[[battery.display]]
threshold = 20

[conda]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = "↕️ "
disabled = false

[status]
symbol = "❌"
map_symbol = true
disabled = false

