[conda]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[java]
version_format = "${raw}"

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
version_format = "${raw}"

[python]
version_format = "${raw}"

[ruby]
version_format = "${raw}"

[rust]
version_format = "${raw}"

[scala]
symbol = " "

[status]
map_symbol = true
disabled = false

