[conda]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[scala]
symbol = " "

[status]
map_symbol = true
disabled = false

